In [1]:
# import numpy and pandas libraries needed
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from scipy import stats
np.random.seed(1)

In [2]:
#loading the dataset

df= pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/lymphography/lymphography.data",header = None,)

In [3]:

df.head()

   0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18
0   3   4   2   1   1   1   1   1   2   1   2   2   2   4   8   1   1   2   2
1   2   3   2   1   1   2   2   1   2   1   3   3   2   3   4   2   2   2   2
2   3   3   2   2   2   2   2   2   2   1   4   3   3   4   8   3   2   2   7
3   3   3   1   1   1   1   2   1   2   1   3   3   4   4   4   3   1   2   6
4   2   3   1   1   1   1   1   1   1   1   2   2   4   3   5   1   2   2   1

In [4]:
#assigning columns to the dataset

df.columns =['class', 'lymphatics', 'block of affere', 'bl. of lymph. c','bl. of lymph. s','by pass','extravasates','regeneration of','early uptake in','lym.nodes dimin','lym.nodes enlar','changes in lym','defect in node','changes in node','changes in stru','special forms','dislocation of','exclusion of no','no. of nodes in']

We selected this data set whether to see the lymphographys are regenerated in the body which helps to keep the body healthy and it depends ion the several factors whether it can be regenrated or not and  now we aree going to predict whether it can re-generate inside based on the other parameters

In [5]:
df

,class,lymphatics,block of affere,bl. of lymph. c,bl. of lymph. s,by pass,extravasates,regeneration of,early uptake in,lym.nodes dimin,lym.nodes enlar,changes in lym,defect in node,changes in node,changes in stru,special forms,dislocation of,exclusion of no,no. of nodes in
0,3,4,2,1,1,1,1,1,2,1,2,2,2,4,8,1,1,2,2
1,2,3,2,1,1,2,2,1,2,1,3,3,2,3,4,2,2,2,2
2,3,3,2,2,2,2,2,2,2,1,4,3,3,4,8,3,2,2,7
3,3,3,1,1,1,1,2,1,2,1,3,3,4,4,4,3,1,2,6
4,2,3,1,1,1,1,1,1,1,1,2,2,4,3,5,1,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,3,3,2,1,1,2,2,1,2,1,2,2,4,3,5,2,2,2,4
144,2,2,1,1,1,1,1,1,1,1,1,1,1,1,3,1,2,2,1
145,3,2,2,1,1,1,2,1,2,1,3,3,3,3,8,3,2,2,4
146,2,2,1,1,1,1,1,1,2,1,2,2,4,2,2,1,2,2,1
147,2,2,2,2,1,2,2,1,2,1,3,3,4,3,4,3,2,2,6

As,we can see the data set is already en-coded and again no need to do en-coding

In [6]:
df.isna().sum()

class              0
lymphatics         0
block of affere    0
bl. of lymph. c    0
bl. of lymph. s    0
by pass            0
extravasates       0
regeneration of    0
early uptake in    0
lym.nodes dimin    0
lym.nodes enlar    0
changes in lym     0
defect in node     0
changes in node    0
changes in stru    0
special forms      0
dislocation of     0
exclusion of no    0
no. of nodes in    0
dtype: int64

We can see there are no missing values in our dataset

In [7]:
# split the data into validation and training set

train_df, test_df = train_test_split(df, test_size=0.3)

# construct datasets for analysis
target = 'regeneration of'
predictors = list(df.columns)
predictors.remove(target)
X = df[predictors]
y = df[target]

Here the traget variable is regeneration of lymphographs inside the body based on the other paramters.

In [8]:
# create the training set and the test set 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=1)

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
#We are doing scaling for train to perform better fitting

scaler = MinMaxScaler()

# transform data
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [11]:

y_train.value_counts()

1    96
2     7
Name: regeneration of, dtype: int64

In [12]:
import imblearn
from imblearn.under_sampling import RandomUnderSampler

sampling= RandomUnderSampler(sampling_strategy = 'majority')
X_train,y_train= sampling.fit_resample(X_train, y_train)

In [13]:
y_train.value_counts()

1    7
2    7
Name: regeneration of, dtype: int64

In [14]:
#Saving the datafiles of train and test into csv 

X_train = pd.DataFrame(X_train)
X_train.to_csv('C:/Users/ssand/OneDrive/Desktop/pre/X_train.csv', index=False)

In [15]:
X_test = pd.DataFrame(X_test)
X_test.to_csv('C:/Users/ssand/OneDrive/Desktop/pre/X_test.csv', index=False)

In [16]:
y_train = pd.DataFrame(y_train)
y_train.to_csv('C:/Users/ssand/OneDrive/Desktop/pre/y_train.csv', index=False)

In [17]:
y_test = pd.DataFrame(y_test)
y_test.to_csv('C:/Users/ssand/OneDrive/Desktop/pre/y_test.csv', index=False)

In [18]:
performance = pd.DataFrame({"model": [], "Accuracy": [], "Precision": [], "Recall": [], "F1": []})

From the above We done Cleaning the data and loading the data to our system with that we also performmed the splitting of data to train and test. we are fitting various models with our data set .

In [19]:
# Explore the dataset
# read the first row of the dataset 
print(df.head())
print(df.columns)
print(df.describe())
print(df.info())

   class  lymphatics  block of affere  bl. of lymph. c  bl. of lymph. s  \
0      3           4                2                1                1
1      2           3                2                1                1
2      3           3                2                2                2
3      3           3                1                1                1
4      2           3                1                1                1

   by pass  extravasates  regeneration of  early uptake in  lym.nodes dimin  \
0        1             1                1                2                1
1        2             2                1                2                1
2        2             2                2                2                1
3        1             2                1                2                1
4        1             1                1                1                1

   lym.nodes enlar  changes in lym  defect in node  changes in node  \
0                2               2               2                4
1                3               3               2                3
2                4               3               3                4
3                3               3               4                4
4                2               2               4                3

   changes in stru  special forms  dislocation of  exclusion of no  \
0                8              1               1                2
1                4              2               2                2
2                8              3               2                2
3                4              3               1                2
4                5              1               2                2

   no. of nodes in
0                2
1                2
2                7
3                6
4                1
Index(['class', 'lymphatics', 'block of affere', 'bl. of lymph. c',
       'bl. of lymph. s', 'by pass', 'extravasates', 'regeneration of',
       'early uptake in', 'lym.nodes dimin', 'lym.nodes enlar',
       'changes in lym', 'defect in node', 'changes in node',
       'changes in stru', 'special forms', 'dislocation of', 'exclusion of no',
       'no. of nodes in'],
      dtype='object')
            class  lymphatics  block of affere  bl. of lymph. c  \
count  148.000000  148.000000       148.000000       148.000000
mean     2.452703    2.743243         1.554054         1.175676
std      0.575396    0.817509         0.498757         0.381836
min      1.000000    1.000000         1.000000         1.000000
25%      2.000000    2.000000         1.000000         1.000000
50%      2.000000    3.000000         2.000000         1.000000
75%      3.000000    3.000000         2.000000         1.000000
max      4.000000    4.000000         2.000000         2.000000

       bl. of lymph. s     by pass  extravasates  regeneration of  \
count       148.000000  148.000000    148.000000       148.000000
mean          1.047297    1.243243      1.506757         1.067568
std           0.212995    0.430498      0.501652         0.251855
min           1.000000    1.000000      1.000000         1.000000
25%           1.000000    1.000000      1.000000         1.000000
50%           1.000000    1.000000      2.000000         1.000000
75%           1.000000    1.000000      2.000000         1.000000
max           2.000000    2.000000      2.000000         2.000000

       early uptake in  lym.nodes dimin  lym.nodes enlar  changes in lym  \
count       148.000000       148.000000       148.000000      148.000000
mean          1.702703         1.060811         2.472973        2.398649
std           0.458621         0.313557         0.836627        0.568323
min           1.000000         1.000000         1.000000        1.000000
25%           1.000000         1.000000         2.000000        2.000000
50%           2.000000         1.000000         2.000000        2.000000
75%           2.000000         1.000000         3.000000        3.000000
max           2.000000         3.000000         4.000000        3.000000

       defect in node  changes in node  changes in stru  special forms  \
count      148.000000       148.000000       148.000000     148.000000
mean         2.966216         2.804054         5.216216       2.331081
std          0.868305         0.761834         2.171368       0.777126
min          1.000000         1.000000         1.000000       1.000000
25%          2.000000         2.000000         4.000000       2.000000
50%          3.000000         3.000000         5.000000       3.000000
75%          4.000000         3.000000         8.000000       3.000000
max          4.000000         4.000000         8.000000       3.000000

       dislocation of  exclusion of no  no. of nodes in
count      148.000000       148.000000       148.000000
mean         1.662162         1.790541         2.601351
std          0.474579         0.408305         1.905023
min          1.000000         1.000000         1.000000
25%          1.000000         2.000000         1.000000
50%          2.000000         2.000000         2.000000
75%          2.000000         2.000000         3.000000
max          2.000000         2.000000         8.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   class            148 non-null    int64
 1   lymphatics       148 non-null    int64
 2   block of affere  148 non-null    int64
 3   bl. of lymph. c  148 non-null    int64
 4   bl. of lymph. s  148 non-null    int64
 5   by pass          148 non-null    int64
 6   extravasates     148 non-null    int64
 7   regeneration of  148 non-null    int64
 8   early uptake in  148 non-null    int64
 9   lym.nodes dimin  148 non-null    int64
 10  lym.nodes enlar  148 non-null    int64
 11  changes in lym   148 non-null    int64
 12  defect in node   148 non-null    int64
 13  changes in node  148 non-null    int64
 14  changes in stru  148 non-null    int64
 15  special forms    148 non-null    int64
 16  dislocation of   148 non-null    int64
 17  exclusion of no  148 non-null    int64
 18  no. of nodes in  148 non-null    int64
dtypes: int64(19)
memory usage: 22.1 KB
None